modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="oresplus" #mandatory

version="1.3" #mandatory

displayName="Ores+" #mandatory

logoFile="oreslogo.jpg" #optional

credits="Thanks for the Ores+ Mod goes to damqn4etoBG and PandaGamez" #optional

authors="damqn4etoBG and PandaGamez" #optional

description='''
This mod adds new ores and bosses to the game.
'''

[[dependencies.examplemod]] #optional
    modId="oresplus" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="oresplus"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"